// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { LeaderUnit } from '../mmo/leader-unit.js';


export class CellRoomUnit {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CellRoomUnit {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCellRoomUnit(bb:flatbuffers.ByteBuffer, obj?:CellRoomUnit):CellRoomUnit {
  return (obj || new CellRoomUnit()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCellRoomUnit(bb:flatbuffers.ByteBuffer, obj?:CellRoomUnit):CellRoomUnit {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CellRoomUnit()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cellRoomId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

playerCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

frameNumber():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

leaders(index: number, obj?:LeaderUnit):LeaderUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new LeaderUnit()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

leadersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startCellRoomUnit(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addCellRoomId(builder:flatbuffers.Builder, cellRoomId:number) {
  builder.addFieldInt32(0, cellRoomId, 0);
}

static addPlayerCount(builder:flatbuffers.Builder, playerCount:number) {
  builder.addFieldInt32(1, playerCount, 0);
}

static addFrameNumber(builder:flatbuffers.Builder, frameNumber:number) {
  builder.addFieldInt32(2, frameNumber, 0);
}

static addLeaders(builder:flatbuffers.Builder, leadersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, leadersOffset, 0);
}

static createLeadersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLeadersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endCellRoomUnit(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCellRoomUnit(builder:flatbuffers.Builder, cellRoomId:number, playerCount:number, frameNumber:number, leadersOffset:flatbuffers.Offset):flatbuffers.Offset {
  CellRoomUnit.startCellRoomUnit(builder);
  CellRoomUnit.addCellRoomId(builder, cellRoomId);
  CellRoomUnit.addPlayerCount(builder, playerCount);
  CellRoomUnit.addFrameNumber(builder, frameNumber);
  CellRoomUnit.addLeaders(builder, leadersOffset);
  return CellRoomUnit.endCellRoomUnit(builder);
}
}
