// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MessageType } from '../mmo/message-type.js';
import { Vec2 } from '../mmo/vec2.js';


export class ChildUpdateCommandMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChildUpdateCommandMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChildUpdateCommandMessage(bb:flatbuffers.ByteBuffer, obj?:ChildUpdateCommandMessage):ChildUpdateCommandMessage {
  return (obj || new ChildUpdateCommandMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChildUpdateCommandMessage(bb:flatbuffers.ByteBuffer, obj?:ChildUpdateCommandMessage):ChildUpdateCommandMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChildUpdateCommandMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():MessageType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MessageType.Unknown;
}

from():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

childId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

position(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Vec2()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

hp():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

mp():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startChildUpdateCommandMessage(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addType(builder:flatbuffers.Builder, type:MessageType) {
  builder.addFieldInt8(0, type, MessageType.Unknown);
}

static addFrom(builder:flatbuffers.Builder, from:number) {
  builder.addFieldInt32(1, from, 0);
}

static addChildId(builder:flatbuffers.Builder, childId:number) {
  builder.addFieldInt32(2, childId, 0);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, positionOffset, 0);
}

static addHp(builder:flatbuffers.Builder, hp:number) {
  builder.addFieldInt8(4, hp, 0);
}

static addMp(builder:flatbuffers.Builder, mp:number) {
  builder.addFieldInt8(5, mp, 0);
}

static endChildUpdateCommandMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
