// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { AddChildCommandMessage } from '../mmo/add-child-command-message.js';
import { ChildUpdateCommandMessage } from '../mmo/child-update-command-message.js';
import { MoveCommandMessage } from '../mmo/move-command-message.js';
import { RemoveChildCommandMessage } from '../mmo/remove-child-command-message.js';
import { SpawnCommandMessage } from '../mmo/spawn-command-message.js';
import { UnSpawnCommandMessage } from '../mmo/un-spawn-command-message.js';


export enum CommandUnion {
  NONE = 0,
  MoveCommandMessage = 1,
  UnSpawnCommandMessage = 2,
  SpawnCommandMessage = 3,
  AddChildCommandMessage = 4,
  ChildUpdateCommandMessage = 5,
  RemoveChildCommandMessage = 6
}

export function unionToCommandUnion(
  type: CommandUnion,
  accessor: (obj:AddChildCommandMessage|ChildUpdateCommandMessage|MoveCommandMessage|RemoveChildCommandMessage|SpawnCommandMessage|UnSpawnCommandMessage) => AddChildCommandMessage|ChildUpdateCommandMessage|MoveCommandMessage|RemoveChildCommandMessage|SpawnCommandMessage|UnSpawnCommandMessage|null
): AddChildCommandMessage|ChildUpdateCommandMessage|MoveCommandMessage|RemoveChildCommandMessage|SpawnCommandMessage|UnSpawnCommandMessage|null {
  switch(CommandUnion[type]) {
    case 'NONE': return null; 
    case 'MoveCommandMessage': return accessor(new MoveCommandMessage())! as MoveCommandMessage;
    case 'UnSpawnCommandMessage': return accessor(new UnSpawnCommandMessage())! as UnSpawnCommandMessage;
    case 'SpawnCommandMessage': return accessor(new SpawnCommandMessage())! as SpawnCommandMessage;
    case 'AddChildCommandMessage': return accessor(new AddChildCommandMessage())! as AddChildCommandMessage;
    case 'ChildUpdateCommandMessage': return accessor(new ChildUpdateCommandMessage())! as ChildUpdateCommandMessage;
    case 'RemoveChildCommandMessage': return accessor(new RemoveChildCommandMessage())! as RemoveChildCommandMessage;
    default: return null;
  }
}

export function unionListToCommandUnion(
  type: CommandUnion, 
  accessor: (index: number, obj:AddChildCommandMessage|ChildUpdateCommandMessage|MoveCommandMessage|RemoveChildCommandMessage|SpawnCommandMessage|UnSpawnCommandMessage) => AddChildCommandMessage|ChildUpdateCommandMessage|MoveCommandMessage|RemoveChildCommandMessage|SpawnCommandMessage|UnSpawnCommandMessage|null, 
  index: number
): AddChildCommandMessage|ChildUpdateCommandMessage|MoveCommandMessage|RemoveChildCommandMessage|SpawnCommandMessage|UnSpawnCommandMessage|null {
  switch(CommandUnion[type]) {
    case 'NONE': return null; 
    case 'MoveCommandMessage': return accessor(index, new MoveCommandMessage())! as MoveCommandMessage;
    case 'UnSpawnCommandMessage': return accessor(index, new UnSpawnCommandMessage())! as UnSpawnCommandMessage;
    case 'SpawnCommandMessage': return accessor(index, new SpawnCommandMessage())! as SpawnCommandMessage;
    case 'AddChildCommandMessage': return accessor(index, new AddChildCommandMessage())! as AddChildCommandMessage;
    case 'ChildUpdateCommandMessage': return accessor(index, new ChildUpdateCommandMessage())! as ChildUpdateCommandMessage;
    case 'RemoveChildCommandMessage': return accessor(index, new RemoveChildCommandMessage())! as RemoveChildCommandMessage;
    default: return null;
  }
}
