// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MessageType } from '../mmo/message-type.js';


export class CommandMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CommandMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCommandMessage(bb:flatbuffers.ByteBuffer, obj?:CommandMessage):CommandMessage {
  return (obj || new CommandMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCommandMessage(bb:flatbuffers.ByteBuffer, obj?:CommandMessage):CommandMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CommandMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():MessageType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MessageType.Unknown;
}

from():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startCommandMessage(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addType(builder:flatbuffers.Builder, type:MessageType) {
  builder.addFieldInt8(0, type, MessageType.Unknown);
}

static addFrom(builder:flatbuffers.Builder, from:number) {
  builder.addFieldInt32(1, from, 0);
}

static endCommandMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCommandMessage(builder:flatbuffers.Builder, type:MessageType, from:number):flatbuffers.Offset {
  CommandMessage.startCommandMessage(builder);
  CommandMessage.addType(builder, type);
  CommandMessage.addFrom(builder, from);
  return CommandMessage.endCommandMessage(builder);
}
}
