// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CommandUnion, unionToCommandUnion, unionListToCommandUnion } from '../mmo/command-union.js';


export class FrameInfo {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FrameInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFrameInfo(bb:flatbuffers.ByteBuffer, obj?:FrameInfo):FrameInfo {
  return (obj || new FrameInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFrameInfo(bb:flatbuffers.ByteBuffer, obj?:FrameInfo):FrameInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FrameInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

frameNumber():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

randomSeed():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

timestamp():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

deltaTime():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

commandsType(index: number):CommandUnion|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : null;
}

commandsTypeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

commandsTypeArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

commands(index: number, obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__union(obj, this.bb!.__vector(this.bb_pos + offset) + index * 4) : null;
}

commandsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startFrameInfo(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addFrameNumber(builder:flatbuffers.Builder, frameNumber:number) {
  builder.addFieldInt32(0, frameNumber, 0);
}

static addRandomSeed(builder:flatbuffers.Builder, randomSeed:number) {
  builder.addFieldInt32(1, randomSeed, 0);
}

static addTimestamp(builder:flatbuffers.Builder, timestamp:number) {
  builder.addFieldInt32(2, timestamp, 0);
}

static addDeltaTime(builder:flatbuffers.Builder, deltaTime:number) {
  builder.addFieldFloat32(3, deltaTime, 0.0);
}

static addCommandsType(builder:flatbuffers.Builder, commandsTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, commandsTypeOffset, 0);
}

static createCommandsTypeVector(builder:flatbuffers.Builder, data:CommandUnion[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startCommandsTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addCommands(builder:flatbuffers.Builder, commandsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, commandsOffset, 0);
}

static createCommandsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCommandsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endFrameInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


static createFrameInfo(builder:flatbuffers.Builder, frameNumber:number, randomSeed:number, timestamp:number, deltaTime:number, commandsTypeOffset:flatbuffers.Offset, commandsOffset:flatbuffers.Offset):flatbuffers.Offset {
  FrameInfo.startFrameInfo(builder);
  FrameInfo.addFrameNumber(builder, frameNumber);
  FrameInfo.addRandomSeed(builder, randomSeed);
  FrameInfo.addTimestamp(builder, timestamp);
  FrameInfo.addDeltaTime(builder, deltaTime);
  FrameInfo.addCommandsType(builder, commandsTypeOffset);
  FrameInfo.addCommands(builder, commandsOffset);
  return FrameInfo.endFrameInfo(builder);
}
}
