// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PlayerUnit } from '../mmo/player-unit.js';


export class GlobalRoomState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GlobalRoomState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGlobalRoomState(bb:flatbuffers.ByteBuffer, obj?:GlobalRoomState):GlobalRoomState {
  return (obj || new GlobalRoomState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGlobalRoomState(bb:flatbuffers.ByteBuffer, obj?:GlobalRoomState):GlobalRoomState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GlobalRoomState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

serverVersion():string|null
serverVersion(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
serverVersion(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

onlinePlayerCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

uptimeSeconds():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

players(index: number, obj?:PlayerUnit):PlayerUnit|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new PlayerUnit()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

playersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGlobalRoomState(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addServerVersion(builder:flatbuffers.Builder, serverVersionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, serverVersionOffset, 0);
}

static addOnlinePlayerCount(builder:flatbuffers.Builder, onlinePlayerCount:number) {
  builder.addFieldInt32(1, onlinePlayerCount, 0);
}

static addUptimeSeconds(builder:flatbuffers.Builder, uptimeSeconds:number) {
  builder.addFieldInt32(2, uptimeSeconds, 0);
}

static addPlayers(builder:flatbuffers.Builder, playersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, playersOffset, 0);
}

static createPlayersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPlayersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGlobalRoomState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishGlobalRoomStateBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedGlobalRoomStateBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createGlobalRoomState(builder:flatbuffers.Builder, serverVersionOffset:flatbuffers.Offset, onlinePlayerCount:number, uptimeSeconds:number, playersOffset:flatbuffers.Offset):flatbuffers.Offset {
  GlobalRoomState.startGlobalRoomState(builder);
  GlobalRoomState.addServerVersion(builder, serverVersionOffset);
  GlobalRoomState.addOnlinePlayerCount(builder, onlinePlayerCount);
  GlobalRoomState.addUptimeSeconds(builder, uptimeSeconds);
  GlobalRoomState.addPlayers(builder, playersOffset);
  return GlobalRoomState.endGlobalRoomState(builder);
}
}
