// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum MessageType {
  Unknown = 0,
  Frame = 1,
  Move = 2,
  SkillUse = 3,
  Chat = 4,
  Stop_Move = 5,
  addChild = 6,
  removeChild = 7,
  Spawn = 250,
  Despawn = 251,
  Room_Full = 252,
  Update_State = 252,
  Heartbeat = 253,
  Sync_Request = 254
}
