// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MessageType } from '../mmo/message-type.js';


export class RemoveChildCommandMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RemoveChildCommandMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRemoveChildCommandMessage(bb:flatbuffers.ByteBuffer, obj?:RemoveChildCommandMessage):RemoveChildCommandMessage {
  return (obj || new RemoveChildCommandMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRemoveChildCommandMessage(bb:flatbuffers.ByteBuffer, obj?:RemoveChildCommandMessage):RemoveChildCommandMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RemoveChildCommandMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():MessageType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MessageType.Unknown;
}

from():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

childId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startRemoveChildCommandMessage(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addType(builder:flatbuffers.Builder, type:MessageType) {
  builder.addFieldInt8(0, type, MessageType.Unknown);
}

static addFrom(builder:flatbuffers.Builder, from:number) {
  builder.addFieldInt32(1, from, 0);
}

static addChildId(builder:flatbuffers.Builder, childId:number) {
  builder.addFieldInt32(2, childId, 0);
}

static endRemoveChildCommandMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRemoveChildCommandMessage(builder:flatbuffers.Builder, type:MessageType, from:number, childId:number):flatbuffers.Offset {
  RemoveChildCommandMessage.startRemoveChildCommandMessage(builder);
  RemoveChildCommandMessage.addType(builder, type);
  RemoveChildCommandMessage.addFrom(builder, from);
  RemoveChildCommandMessage.addChildId(builder, childId);
  return RemoveChildCommandMessage.endRemoveChildCommandMessage(builder);
}
}
