// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RoleType {
  Unknown = 0,
  Player = 1,
  NPC = 2,
  Monster = 3,
  Boss = 4,
  Pet = 5,
  Summon = 6,
  Ally = 7,
  Merchant = 8,
  QuestGiver = 9,
  Other = 10,
  Bullet = 11,
  Mouse = 12,
  ViewArea = 13
}
