// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MessageType } from '../mmo/message-type.js';
import { Vec2 } from '../mmo/vec2.js';


export class SpawnCommandMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SpawnCommandMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSpawnCommandMessage(bb:flatbuffers.ByteBuffer, obj?:SpawnCommandMessage):SpawnCommandMessage {
  return (obj || new SpawnCommandMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSpawnCommandMessage(bb:flatbuffers.ByteBuffer, obj?:SpawnCommandMessage):SpawnCommandMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SpawnCommandMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():MessageType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MessageType.Unknown;
}

from():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

position(obj?:Vec2):Vec2|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Vec2()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSpawnCommandMessage(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addType(builder:flatbuffers.Builder, type:MessageType) {
  builder.addFieldInt8(0, type, MessageType.Unknown);
}

static addFrom(builder:flatbuffers.Builder, from:number) {
  builder.addFieldInt32(1, from, 0);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(2, id, 0);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, positionOffset, 0);
}

static endSpawnCommandMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
