// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { MessageType } from '../mmo/message-type.js';


export class UnSpawnCommandMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UnSpawnCommandMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnSpawnCommandMessage(bb:flatbuffers.ByteBuffer, obj?:UnSpawnCommandMessage):UnSpawnCommandMessage {
  return (obj || new UnSpawnCommandMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnSpawnCommandMessage(bb:flatbuffers.ByteBuffer, obj?:UnSpawnCommandMessage):UnSpawnCommandMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnSpawnCommandMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

type():MessageType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : MessageType.Unknown;
}

from():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

id():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startUnSpawnCommandMessage(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addType(builder:flatbuffers.Builder, type:MessageType) {
  builder.addFieldInt8(0, type, MessageType.Unknown);
}

static addFrom(builder:flatbuffers.Builder, from:number) {
  builder.addFieldInt32(1, from, 0);
}

static addId(builder:flatbuffers.Builder, id:number) {
  builder.addFieldInt32(2, id, 0);
}

static endUnSpawnCommandMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUnSpawnCommandMessage(builder:flatbuffers.Builder, type:MessageType, from:number, id:number):flatbuffers.Offset {
  UnSpawnCommandMessage.startUnSpawnCommandMessage(builder);
  UnSpawnCommandMessage.addType(builder, type);
  UnSpawnCommandMessage.addFrom(builder, from);
  UnSpawnCommandMessage.addId(builder, id);
  return UnSpawnCommandMessage.endUnSpawnCommandMessage(builder);
}
}
